source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BlinkingLable_Example', :exclusive => true do
  pod "BlinkingLable", :path => "../"
end

target 'BlinkingLable_Tests', :exclusive => true do
  pod "BlinkingLable", :path => "../"

  
end
